name: Set up node envirnoment
branding:
  icon: eye
  color: blue
setup-node:
  name: Set up node envirnoment
  runs-on: ubuntu-latest

  steps:
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Set up npm
      run : npm install
