name: Update production server

on:
  push:
    branches:
      - feature/actions

jobs:
  lint:
    name: Check code base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: lint
        uses: ./.github/actions/lint

  deploy:
    name: Deploy on production server
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Set up node
        uses: ./.github/actions/setup-node

      - name: Set up sshpass and npm
        run : |
          sudo apt-get install sshpass
          npm install

      - name: Run build
        run : npm run build

      - name: Deploy on dev server
        run : sshpass -p ${{ secrets.SERVER_PASS }} rsync -e "ssh -o StrictHostKeyChecking=no" -rltzh -O --delete dist/rubic/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/dev_rubic_exchange/frontend
