name: Check code quality

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Check code base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: feature/actions

      - name: lint
        uses: ./.github/actions/lint
