name: Develop branch

# This action works on push
on:
  push:
    branches:
      - develop

jobs:
#  test:
#    name: Run test
#    runs-on: ubuntu-latest
#
#    steps:
#        # Copy repo from develop branch
#      - uses: actions/checkout@v2
#        with:
#          ref: develop
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '15'
#
#      - name: Run install
#        run : npm install
#
#      - name: Run test
#        run : npm run test

  lint:
    name: Check code base
    runs-on: ubuntu-latest
#    needs: [test]

    steps:
        # Copy repo from develop branch
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Set up npm
        run : npm install

      - name: Run lint
        run : npm run lint

      - name: Run lint css
        run : npm run lint-css

  deploy:
    name: Deploy on develop server
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
        # Copy repo from develop branch
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Set up sshpass and npm
        run : |
          sudo apt-get install sshpass
          npm install

      - name: Run build
        run : npm run build

      - name: Deploy on dev server
        run : sshpass -p ${{ secrets.SERVER_PASS }} rsync -e "ssh -o StrictHostKeyChecking=no" -rltzhP -O --delete dist/rubic/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/../frontend/swaps
