name: 'Read .nvmrc'
description: 'Read node version from .nvmrc file'
outputs:
  node_version:
    description: "Node version from .nvmrc"
    value: ${{ steps.nvmrc_content.outputs.node_version }}
runs:
  using: "composite"
  steps:
    - id: nvmrc_content
      run: echo ::set-output name=node_version::$(cat .nvmrc)
      shell: bash
